### ISSUE TITLE
Error starting RPCMirror

### ISSUE THREAD

**Issue by rafael5** [vistadataproject/RPCMirror#1]
after git cloning the repository, I attempted to start with the following results:

[RPCMirror]$ npm start

> @vistadataproject/rpc-mirror@0.1.0 start /Users/rafael/git/rafael5/vdp/RPCMirror
> node src/index.js

events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'logs/mirror.log'
Emitted 'error' event at:
    at WriteStream.onStreamError (/Users/rafael/git/rafael5/vdp/RPCMirror/node_modules/bunyan/lib/bunyan.js:627:18)
    at WriteStream.emit (events.js:193:13)
    at /Users/rafael/git/rafael5/vdp/RPCMirror/node_modules/graceful-fs/graceful-fs.js:228:14
    at /Users/rafael/git/rafael5/vdp/RPCMirror/node_modules/graceful-fs/graceful-fs.js:258:16
    at FSReqCallback.args [as oncomplete] (fs.js:145:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @vistadataproject/rpc-mirror@0.1.0 start: `node src/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @vistadataproject/rpc-mirror@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rafael/.npm/_logs/2019-04-03T04_34_37_992Z-debug.log

**Comment by mfuroyama** [comment]
This was absolutely a bug! I forgot that Bunyan (the logging module used here) doesn't bother creating non-existent target directories for file-based output stream artifacts! With its default (developer) configuration, the **RPC Mirror** will attempt to write out a log file to `./logs/mirror.log`. Unfortunately, if you didn't have the `logs` directory created, you'd experience a crash like above.

I just pushed up a changed to the repo that will ensure the directories exist before the log file gets created. If you do a `git pull` and try again, it should work!

**Comment by mfuroyama** [comment]
I'm going to close this issue, if that's okay. The code updates address this and this error doesn't occur anymore! Thanks!!
